### ISSUE TITLE
Question about the input range

### ISSUE THREAD

**Issue by kacey-yang** [razvanmarinescu/brain-coloring#22]
Hello,

I just have a quick question regarding the input range.

I just wanted to confirm that if BrainPainter only takes input values range from 0 - 3?
So, it means that BrainPainter cannot handle input range from 0 - m, where m represents any positive integer?

Thanks!

**Comment by kacey-yang** [comment]
Sorry I am quite urgent on this. Hope I can hear back from you soon!
Thank you!

**Comment by razvanmarinescu** [comment]
On the website GUI there's a max of 5 colours I think. 

For more than 5, you can use the source code (docker install is quickest). The only thing you need to add is more colors to color-list in config.py (e.g. m colors) and it should work right away. Of course, the input biomarkers will need to be in range [0,m].

**Comment by kacey-yang** [comment]
Thanks for your quick reply!

I just want to confirm a few things.
1) The webpage cannot handle integers larger than 5?
2) Positive number m should be an integer, rather than non-integers?
3) The assignment of colors to values is kind of discrete? 

Is it correct?

Thank you!

**Comment by kacey-yang** [comment]
Honestly, I don't quite understand why BrainPainter webpage can only take input range from 0-3, 0-4, or 0-5?

Previously, when I used the webpage, I can plot 0-3 using 5 colors.
It seems that, if the # of colors is SMALLER than the max integer, it won't work?

Thanks!

**Comment by razvanmarinescu** [comment]
> It seems that, if the # of colors is SMALLER than the max integer, it won't work?

Indeed, that probably won't work. 


The webpage cannot handle integers larger than 5?

Yes.

Positive number m should be an integer, rather than non-integers?

Yes, needs to be integer. But you max value in the input biomarkers can be non-integer. E.g. you provide colors in range 0-4, but your data only goes from 0-2.8. That should work. 

The assignment of colors to values is kind of discrete?

I don't get the question.

Finally, the source code for the website is here: https://github.com/razvanmarinescu/brain-coloring-website. You can reproduce it exactly on your local machine, after setup, and you're welcome to send a pull request to fix any issues you find.
