### ISSUE TITLE
Top and bottom view of inflated brain type is wrong

### ISSUE THREAD

**Issue by BailiangJ** [razvanmarinescu/brain-coloring#31]
Hi @razvanmarinescu ,

Thanks a lot for the great software.

The top/bottom view of brain_type='inflated' I am getting looks wrong.

![figure](https://github.com/razvanmarinescu/brain-coloring/assets/33227998/7cc3cf06-a10d-409c-9dd7-03f70d0e9c58)

**Comment by razvanmarinescu** [comment]
Glad it's useful! Have you tried running brainpainter from source? Attach here a minimal working example as a zip, with brainpainter and the CSV biomarker table? We can't debug it otherwise.

**Comment by BailiangJ** [comment]
Hi @razvanmarinescu ,

Thanks for the reply.

I am using the docker with the latest repo to generate the figures.

I set **BRAIN_TYPE = 'inflated', IMG_TYPE='top'**, use the DK_template as input, and run with the default Makefile .

And I get

![top_Image_0](https://github.com/razvanmarinescu/brain-coloring/assets/33227998/2814082a-4c3d-42b1-8f74-2c51ca13ec51)
![top_Image_1](https://github.com/razvanmarinescu/brain-coloring/assets/33227998/f0d52f12-f1dc-4610-953f-af583a0b8b21)

**Comment by jvengosh** [comment]
Hi there!

After some digging, here's what I've found. It seems that the inflated brain type's process does not correctly preserve the shape of the brain in these views. Interestingly, what it's doing is squishing the brain (take a look at a cortical-inner-left or right view to see what I mean) and the issue is because of the polygon files used in the inflated brain type.

I'll attach an example using the same data with multiple views. I would suggest using a different brain type because the perspectives are the same for each and the information is a bit more viewable in the others. The only unintended thing seems to be the "unsquished" bits on the bottom that affect the top and bottom views.

Let me know if you need anything else!

![image](https://github.com/razvanmarinescu/brain-coloring/assets/125224893/8cf00c80-b3d7-4449-bff5-b33d88b918bd)

**Comment by razvanmarinescu** [comment]
ah yes, so if you change from inflated to the standard option (I think "pial"), that should work. We didn't test extensively with the inflated or white-matter formats

**Comment by BailiangJ** [comment]
Hi @jvengosh @razvanmarinescu ,

Thanks a lot!

Yes, it's just only the top/bottom views of inflated having a problem. The rest are still informative and good to use.:)
