### ISSUE TITLE
Show brain's left side?

### ISSUE THREAD

**Issue by pfdamasceno** [razvanmarinescu/brain-coloring#4]
Hi, 

Currently it seems the camera only shows the right side of brain (and only 1/2 of the regions are needed in the csv file), but at times it would be useful to show the differences between right vs left brain (e.g. non-symmetrical diseases). Is there a supported way to do this, currently?

Thanks!

**Comment by mrazvan22** [comment]
Yes, it is possible, but you need to modify the source code. So far I didn't implement this feature yet. In blendHelper: CorticalPainter :: setCamera(...), you need to change the camera location and rotation so that it looks at the brain from the left side. You need to change these:

scene.camera.location = ..
scene.camera.rotation_euler = ...

To get enough lightning on the other side, you will also need to change the location of the lamps in setLamp().  The easiest way to find the right coordinates for all of these is to run the script interactively using Blender, and then move the camera and lamps manually using the mouse, and see how the viewpoint/rendering updates. Then you can print out the coordinates and put them in the script. 

If you end up modifying it, I suggest you create a new class CorticalPainterLeft, and instantiate this class for the new IMG_TYPE in blendCreateSnapshot(), on lines 89-120. Send me a pull request when done, and I'll merge it into master
