### ISSUE TITLE
Color bar adjustment using browser

### ISSUE THREAD

**Issue by kacey-yang** [razvanmarinescu/brain-coloring#7]
I am having a problem with the color bar. 
I cannot make the color bar range from 0-3 using the browser. 

Is possible to adjust the range of color bar from the browser? 
Or, I have to install the docker to adjust it?

**Comment by vmallela0** [comment]
The easiest way to change the range would be to edit the report.tex file that comes with the figures folder when you download your images from the website. Delete the last few lines in the LaTeX that uses '\draw', '\shade' and '\definecolor' for the 4 marker you are changing. (To edit LaTeX code you can use websites such as overleaf.com). In the future, we will add more flexibility with the color bar feature so that you can change this from the browser. 

If you have any more trouble with this, feel free to reach out to us via email.

**Comment by kacey-yang** [comment]
Thanks! I tried editing the latex code and it works!
